### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by FILIPJEKRAL** [milsnkll/project-x#3]
Velmi doporučuji změnit jazyk na češtinu. Když rozkliknu práci tak text je prazvláštně zdvojený a tudíž nečitelný

**Comment by milsnkll** [comment]
ne

**Comment by milsnkll** [comment]
noo, mas pravdu

**Comment by milsnkll** [comment]
uz opraveno! :)

**Comment by FILIPJEKRAL** [comment]
šikovný ste
